version: '3.9'

services:
  web:
    build: .
    command: bundle exec rspec
    env_file:
      - .env.test
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kirvano_test
    ports:
      - "5434:5432"

  redis:
    image: redis:7
