default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= Sidekiq.server? ? ENV.fetch('SIDEKIQ_CONCURRENCY', 10) : ENV.fetch('RAILS_MAX_THREADS', 5) %>
  reaping_frequency: <%= ENV.fetch('DB_POOL_REAPING_FREQUENCY', 30) %>
  variables:
    statement_timeout: <%= ENV.fetch('POSTGRES_STATEMENT_TIMEOUT', '14s') %>

development:
  <<: *default
  # Performance optimizations for local development
  timeout: 5000
  connect_timeout: 2
  checkout_timeout: 2
  variables:
    statement_timeout: <%= ENV.fetch('POSTGRES_STATEMENT_TIMEOUT', '5s') %>
    lock_timeout: '3s'
    idle_in_transaction_session_timeout: '10s'

test:
  <<: *default

production:
  <<: *default
