default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= Sidekiq.server? ? ENV.fetch('SIDEKIQ_CONCURRENCY', 10) : ENV.fetch('RAILS_MAX_THREADS', 5) %>
  reaping_frequency: <%= ENV.fetch('DB_POOL_REAPING_FREQUENCY', 30) %>
  variables:
    statement_timeout: <%= ENV.fetch('POSTGRES_STATEMENT_TIMEOUT', '14s') %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
